# Use root/example as user/password credentials
version: '3.1'

services:

  api:
    image: node:12
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: node dist/apps/nest-app/main.js
    ports: 
      - 3000:3000
    
  ressourcen:
    image: node:12
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: node dist/apps/ressourcen/main.js
    depends_on:
      - db
      
  auftraege:
    image: node:12
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: node dist/apps/auftraege/main.js
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: microstuff
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql


  adminer:
    image: adminer
    restart: always
    depends_on:
      - db

    ports:
      - 8080:8080
